services:
  hardhat-node:
    image: node:20-alpine
    working_dir: /app
    command: ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app
    restart: unless-stopped
